### PR TITLE
Add Freeswitch Docker image

### PR DESCRIPTION
**Pull request by JayH5**
Freeswitch packages are only available for Debian (and they are not Ubuntu-compatible).

Freeswitch has various problems running under Docker with standard bridge networking, but things should work better with host networking as individual ports do not need to be exposed. Using host networking makes it difficult to use the image under Marathon - such an image would rather be launched on a dedicated machine using supervisor.

This may be the easiest way to get Freeswitch running without having a Debian host. Additionally, we can package config with the image like we do for the other parts of the system.

### CODE REVIEW

**Comment by JayH5** [comment]
@jerith: Ready for review.

Also, @rudigiesler, could you have a look at this too? I wanted to make an image based on Jessie instead of Wheezy but couldn't get the freeswitch 1.4 packages to install on Jessie. This is freeswitch 1.6. Hopefully everything still works. If not I can just go back to Wheezy/1.4. Not sure if you have any experience with this?

**Comment by jerith** [comment]
Looks good to me, but I don't know anything about freeswitch.

**Comment by rudigiesler** [comment]
@JayH5 1.6 seems to be quite a big change with a massive changelog that would take forever to read; I don't have any experience with v1.6, no. But we can always go back, and I'm happier trying to see if we can run a newer version. If it does start to rabbithole, we must just note that and change to 1.4.

I see that we're copying config files instead of mounting a directory. I think we might have to do this for freeswitch, as there are a large amount of default config files that come with freeswitch on install.

How are we going about this with the other images? If we're mounting a directory for the other images, maybe we could mount the config directory at a different location than the freeswitch config files, and copy the files over to the freeswitch config folder on runtime? Just an idea to keep everything uniform though.

The PR looks good to me, I'm assuming that the rest of the config files will be added in the private repo.

**Comment by JayH5** [comment]
@rudigiesler we're copying in config files for all the images. Usually that is done in the private repo (there's a PR there for the freeswitch config referenced above). Basically, once an image is built from the dockerconfig repo it should have _everything_ bundled in it - code, config, command to run.

I thought it'd make sense to copy in the module config file here instead of with the rest of the config as this config is common and I think it's also just enabling the modules that we install? If you think it makes more sense with the rest of the config it can be moved there too.

**Comment by rudigiesler** [comment]
@JayH5 Okay that sounds great. If we're making images with everything built in it, then this way sounds best to me.

I think that we should keep anything that doesn't contain password-type things in open repos, so I'm happy that the module config file is here. Unfortunately, from what I remember, all the rest of the files contain things we don't want the outside world to have access to.

:+1: from me. Let's try v1.6 and see if anything breaks.

**Pull request merged**
